DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2014-01-01', @END_DATE = '2017-12-31';

WITH LIST AS 
(
SELECT ISNULL(B.GENDER,'Z') AS [GENDER], DBO.FN_CUS_GET_AGE(ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),GETDATE()) AS [AGE]

	FROM RES_MASTER_DAMO A
	INNER JOIN RES_CUSTOMER_DAMO B ON A.RES_CODE = B.RES_CODE
	INNER JOIN CUS_CUSTOMER C ON B.CUS_NO = C.CUS_NO
	WHERE A.NEW_DATE >= @START_DATE AND A.NEW_DATE< @END_DATE AND A. RES_STATE < 7 AND B.RES_STATE = 0
	)
SELECT A.GENDER AS [성별], LEFT(A.AGE, 1) AS [연령대], COUNT(*) AS [인원수]
FROM LIST A
GROUP BY A. GENDER , LEFT(A.AGE,1)
ORDER BY A. GENDER, LEFT(A.AGE,1) ASC
