DECLARE @START_DATE DATETIME, @END_DATE DATETIME    
SELECT @START_DATE = '2014-01-01', @END_DATE = '2015-01-01';    
	SELECT 	LEFT(CONVERT(VARCHAR(4),A.DEP_DATE,112),4) AS 출발년도    
	--,B.GENDER    
	--,D.SIGN_CODE    
	--,A.NEW_DATE    
	,DATEDIFF(DAY, A.NEW_DATE , A.DEP_DATE) AS 선행예약시점
	,COUNT(*) AS 인원
	FROM RES_MASTER_damo A WITH(NOLOCK)    
	INNER JOIN RES_CUSTOMER_damo B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE    
	INNER JOIN CUS_CUSTOMER_DAMO C WITH(NOLOCK) ON B.CUS_NO = C.CUS_NO    
	INNER JOIN PKG_MASTER D WITH(NOLOCK) ON A.MASTER_CODE = D.MASTER_CODE    
	WHERE A.RES_STATE <=7  AND B.RES_STATE =0    
	AND A.DEP_DATE >= @START_DATE AND A.DEP_DATE < @END_DATE    
	AND A.PRO_TYPE = 1    
	AND B.SALE_PRICE > 0    
	AND B.CUS_NO NOT IN (SELECT CUS_NO FROM TMP_TC_CUS_NO)    
	AND B.BIRTH_DATE IS NOT NULL    
	AND A.MOV_DATE IS NOT NULL   
	--And sign_code = 'A'
	GROUP BY DATEDIFF(DAY, A.NEW_DATE , A.DEP_DATE) ,(CONVERT(VARCHAR(4),A.DEP_DATE,112)), sign_code   
	ORDER BY 선행예약시점 ASC
