DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2014-01-01', @END_DATE = '2017-12-31';

SELECT BB.*, COUNT(*) AS 인원
FROM
(
SELECT
AA.출발년도
,CASE
WHEN AA.AGE IN ('7','8','9','100세 이상') THEN '70대 이상'
ELSE AA.AGE
END AS [연령대]
,AA.SIGN_CODE
, CASE
WHEN AA.선행예약시점 >= 0 AND AA.선행예약시점 < 30 THEN '30일 이전'
WHEN AA.선행예약시점 >= 30 AND AA.선행예약시점 < 60 THEN '30~59일'
WHEN AA.선행예약시점 >= 60 AND AA.선행예약시점 < 90 THEN '60~89일'
WHEN AA.선행예약시점 >= 90 AND AA.선행예약시점 < 120 THEN '90~119일'
WHEN AA.선행예약시점 >= 120 AND AA.선행예약시점 < 150 THEN '120~149일'
WHEN AA.선행예약시점 >= 150 AND AA.선행예약시점 < 180 THEN '150~179일'
WHEN AA.선행예약시점 >= 180 THEN '180일 이후'
END AS 선행예약시점
FROM

(
SELECT 
--DBO.BD_CUS_GET_AGE(B.BIRTH_DATE,A.DEP_DATE,1) AS 연령
LEFT(CONVERT(VARCHAR(10),A.DEP_DATE,112),4) AS 출발년도
, CASE 
WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),@START_DATE)+1)=1 THEN '10세 미만'
WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),@START_DATE)+1)=3 THEN '100세 이상'
ELSE LEFT((DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),@START_DATE)+1),1)
END AS AGE
,B.GENDER
,D.SIGN_CODE
,A.NEW_DATE
,DATEDIFF(DAY, A.NEW_DATE , A.DEP_DATE) AS 선행예약시점
FROM RES_MASTER_damo A
INNER JOIN RES_CUSTOMER_damo B ON A.RES_CODE = B.RES_CODE
INNER JOIN CUS_CUSTOMER C ON B.CUS_NO = C.CUS_NO
INNER JOIN PKG_MASTER D ON A.MASTER_CODE = D.MASTER_CODE
WHERE A.RES_STATE <=7  AND B.RES_STATE =0
AND A.DEP_DATE >= @START_DATE AND A.DEP_DATE < @END_DATE
AND A.PRO_TYPE = 1
AND B.SALE_PRICE > 0
AND B.CUS_NO NOT IN (SELECT CUS_NO FROM TMP_TC_CUS_NO)
AND B.BIRTH_DATE IS NOT NULL
AND A.MOV_DATE IS NOT NULL
) AA
WHERE 선행예약시점 <= 180 AND 선행예약시점 >=0
) BB

GROUP BY BB.출발년도, BB.연령대, BB.SIGN_CODE, BB.선행예약시점
ORDER BY BB.출발년도, BB.연령대, BB.SIGN_CODE, BB.선행예약시점 DESC ;
