-- LIST A. 예약자 중에 출발하지 않은 예약자 정보 
DECLARE @START_DATE DATETIME, @END_DATE DATETIME		
SELECT @START_DATE = '2017-02-01', @END_DATE = '2017-03-01';
WITH LIST AS (
	SELECT A.RES_CODE, A.RES_NAME, 
	      CASE WHEN LEN(DATEDIFF(YEAR,ISNULL(A.BIRTH_DATE,B.BIRTH_DATE),@START_DATE)+1)=1 THEN '10세 미만'	
		  WHEN LEN(DATEDIFF(YEAR,ISNULL(A.BIRTH_DATE,B.BIRTH_DATE),@START_DATE)+1)=3 THEN '100세 이상'
		  ELSE LEFT((DATEDIFF(YEAR,ISNULL(A.BIRTH_DATE,B.BIRTH_DATE),@START_DATE)+1),1)
		  END AS RES_AGE 
		  FROM RES_MASTER_DAMO A WITH(NOLOCK)
	      LEFT JOIN CUS_CUSTOMER_DAMO B WITH(NOLOCK) 
			ON A.CUS_NO = B.CUS_NO AND A.CUS_NO > 1
	      WHERE A.DEP_DATE >= @START_DATE AND A.DEP_DATE < @END_DATE 
		  AND A.RES_STATE <= 7
		  AND NOT EXISTS (SELECT * FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE AND CUS_NAME = A.RES_NAME AND RES_STATE = 0)
	) 


-- **최종 출발자 평균연령 까지 구하기 
SELECT RES_CODE, RES_NAME,RES_AGE,
     (TOTAL_AGE/TOTAL_AGE_CNT) AS AVG_AGE ,  TOTAL_AGE  , TOTAL_AGE_CNT , DBO.FN_RES_GET_RES_COUNT(RES_CODE) AS CUS_CNT 
FROM ( 
-- LIST A 예약정보 중에서 연령대가 올바른 출발자 나이 정보 구하기 예약자정보로 GROUP BY 예약자정보
		SELECT A.RES_CODE, A.RES_NAME, A.RES_AGE , 
			  SUM(DBO.FN_CUS_GET_AGE_BY_BIRTH(B.BIRTH_DATE,@START_DATE) ) AS TOTAL_AGE , 
			  COUNT(*)  AS TOTAL_AGE_CNT
		FROM LIST A 
		INNER JOIN RES_CUSTOMER_DAMO B WITH(NOLOCK)
			ON A.RES_CODE = B.RES_CODE
			AND DBO.FN_CUS_GET_AGE_BY_BIRTH(B.BIRTH_DATE,@START_DATE) BETWEEN 19 AND 99 
		--LEFT JOIN CUS_CUSTOMER_DAMO C WITH(NOLOCK)
		--	ON B.CUS_NO = C.CUS_NO
	    GROUP BY A.RES_NAME, A.RES_CODE, A.RES_AGE
	)T


-- 검증 
--SELECT 
--A.RES_CODE , A.RES_NAME , ISNULL(A.BIRTH_DATE , C.BIRTH_DATE ) AS RES_BIRTH, 
--B.BIRTH_DATE,
--DBO.FN_CUS_GET_AGE_BY_BIRTH(B.BIRTH_DATE,'2017-01-01')
--FROM RES_MASTEr_DAMO A
--	INNER JOIN RES_CUSTOMER_DAMO B 
	--	ON A.RES_CODE = B.RES_CODE 
	--LEFT JOIN CUS_CUSTOMER_DAMO C 
		--ON A.CUS_NO = C.CUS_NO 
		--AND A.CUS_NO > 1 
--WHERE A.RES_CODE = 'RP1612115566'