-- 테이블 생성		
IF OBJECT_ID('TEMPDB..#CUS_LIST') IS NOT NULL		
	DROP TABLE #CUS_LIST;	
CREATE TABLE #CUS_LIST (F_CON DATETIME NOT NULL, L_CON DATETIME NOT NULL, DEP_YEAR INT NOT NULL, CUS_NAME VARCHAR(40) NOT NULL, BIRTH_DATE DATETIME NOT NULL);		
ALTER TABLE #CUS_LIST ADD CONSTRAINT PKG_CUS_LIST2 PRIMARY KEY (F_CON, L_CON, DEP_YEAR, CUS_NAME, BIRTH_DATE);		
		
-- 기준데이터 등록		
INSERT #CUS_LIST (F_CON, L_CON, DEP_YEAR, CUS_NAME, BIRTH_DATE)		
SELECT		
	CONVERT(DATETIME, (CONVERT(VARCHAR(4), (YEAR(A.DEP_DATE)-2)) + '-01-01')) AS [F_CON],	
	CONVERT(DATETIME, (CONVERT(VARCHAR(4), (YEAR(A.DEP_DATE)+1)) + '-01-01')) AS [F_CON],	
	YEAR(A.DEP_DATE) AS [DEP_YEAR], B.CUS_NAME, B.BIRTH_DATE --,COUNT(*) AS [COUNT]	
	FROM RES_MASTER_damo A WITH(NOLOCK)		
    INNER JOIN RES_CUSTOMER_damo B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE		
WHERE A.DEP_DATE >= '2015-01-01' AND A.DEP_DATE < '2017-12-31' AND A.RES_STATE < 7 AND B.RES_STATE IN (0, 3, 4)		
	AND B.SALE_PRICE > 0	
	AND A.PROFIT_TEAM_CODE <> 524 -- 법인고객 제외	
	AND B.CUS_NO > 3000	
	AND B.CUS_NAME IS NOT NULL	
	AND B.BIRTH_DATE IS NOT NULL	
	AND B.CUS_NO NOT IN (SELECT AA.CUS_NO FROM TMP_TC_CUS_NO_INFO AA WITH(NOLOCK))	
	AND B.CUS_NO NOT IN (SELECT AA.CUS_NO FROM COM_EMPLOYEE_MATCHING AA WITH(NOLOCK))	
	AND B.CUS_NAME NOT LIKE '%인솔자%' AND B.CUS_NAME NOT LIKE '%가이드%'	
GROUP BY YEAR(A.DEP_DATE), B.CUS_NAME, B.BIRTH_DATE		
ORDER BY YEAR(A.DEP_DATE), B.CUS_NAME, B.BIRTH_DATE;		
		
		
--SELECT * FROM #CUS_LIST		
		
select * from TMP_TC_CUS_NO_INFO where cus_no = 3694375   		
		
		
WITH TEMP_LIST AS (		
	SELECT YEAR(A.DEP_DATE) AS [REST_YEAR], C.DEP_YEAR, C.CUS_NAME, C.BIRTH_DATE, ROW_NUMBER() OVER (PARTITION BY C.DEP_YEAR, C.CUS_NAME, C.BIRTH_DATE ORDER BY A.DEP_DATE) AS [ROW_NUM]	
		, ISNULL((ISNULL(SALE_PRICE, 0) - ISNULL(DC_PRICE, 0) + ISNULL(CHG_PRICE, 0) + ISNULL(TAX_PRICE, 0) + ISNULL(PENALTY_PRICE, 0) + 0.0), 00) AS [RES_PRICE]
	FROM RES_MASTER_damo A WITH(NOLOCK)	
	INNER JOIN RES_CUSTOMER_damo B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE	
	INNER JOIN #CUS_LIST C ON B.CUS_NAME = C.CUS_NAME AND B.BIRTH_DATE = C.BIRTH_DATE	
	WHERE A.DEP_DATE >= C.F_CON AND A.DEP_DATE < C.L_CON AND A.RES_STATE < 7 AND B.RES_STATE IN (0, 3, 4)	
		AND B.SALE_PRICE > 0
		AND A.PROFIT_TEAM_CODE <> 524 -- 법인고객 제외
		AND B.CUS_NO > 3000
		AND B.CUS_NAME IS NOT NULL
		AND B.BIRTH_DATE IS NOT NULL
		AND B.CUS_NO NOT IN (SELECT AA.CUS_NO FROM TMP_TC_CUS_NO_INFO AA WITH(NOLOCK))
		AND B.CUS_NO NOT IN (SELECT AA.CUS_NO FROM COM_EMPLOYEE_MATCHING AA WITH(NOLOCK))
		AND B.CUS_NAME NOT LIKE '%인솔자%' AND B.CUS_NAME NOT LIKE '%가이드%'
)		
		
SELECT A.DEP_YEAR, A.ROW_NUM, COUNT(*) AS [CUS_LIST], SUM(A.RES_PRICE) AS [TOTAL_PRICE]		
FROM TEMP_LIST A		
WHERE A.REST_YEAR = A.DEP_YEAR		
GROUP BY A.DEP_YEAR, A.ROW_NUM		
ORDER BY A.DEP_YEAR, A.ROW_NUM		
