
DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2013-01-01', @END_DATE = '2013-01-31';
WITH LIST AS 
( 
	SELECT 
		  B.RES_CODE
		, CASE 
			WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1) = 1 THEN '0'
			WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1) = 3 THEN '10'
			ELSE LEFT((DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1),1) END AS 연령대 
		, (SALE_PRICE - DC_PRICE + CHG_PRICE + TAX_PRICE + PENALTY_PRICE) AS 상품가 -- 판매금액 구하는 공식
		--B.SALE_PRICE AS 상품가
		, D.SIGN_CODE AS 지역
	FROM RES_MASTER_DAMO A WITH(NOLOCK)
	INNER JOIN RES_CUSTOMER_DAMO B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE
	INNER JOIN CUS_CUSTOMER_DAMO C WITH(NOLOCK) ON B.CUS_NO = C.CUS_NO
	INNER JOIN PKG_MASTER D WITH(NOLOCK) ON A.MASTER_CODE = D.MASTER_CODE
	WHERE 
		A.DEP_DATE >= @START_DATE 
			AND A.DEP_DATE < @END_DATE 
			AND A.RES_STATE <= 7 AND B.RES_STATE IN ( 0, 3, 4 )
			AND B.CUS_NO NOT IN (SELECT AA.CUS_NO FROM TMP_TC_CUS_NO_INFO AA WITH(NOLOCK))	
			AND B.CUS_NO NOT IN (SELECT AA.CUS_NO FROM COM_EMPLOYEE_MATCHING AA WITH(NOLOCK))	
			AND B.CUS_NAME NOT LIKE '%인솔자%' AND B.CUS_NAME NOT LIKE '%가이드%'	
			AND B.SALE_PRICE > 0
			AND A.PRO_TYPE = 1
)
SELECT 
	  COUNT(RES_CODE) AS CNT
	, 상품가
FROM LIST	
GROUP BY 상품가, 연령대, 지역
HAVING 연령대 = 7  AND 지역 = 'J'
ORDER BY 상품가