DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2017-01-01', @END_DATE = '2018-01-01';

-- 지역 정보
DECLARE @REGION_NAME_LIST VARCHAR(300);
SELECT @REGION_NAME_LIST = STUFF((SELECT ',[' + KOR_NAME + ']' AS [text()] FROM PUB_REGION WITH(NOLOCK) FOR XML PATH('')), 1, 1, ''); 

WITH LIST AS 
( 
	SELECT 
		LEFT(CONVERT(VARCHAR(10),A.DEP_DATE,121),7) AS 출발년도
		,CASE 
			WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1) = 1 THEN '0'
			WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1) = 3 THEN '10'
			ELSE LEFT((DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1),1) END AS AGE 
			, ISNULL(B.SALE_PRICE, 0) AS [SUM_SALE_PRICE]
			, ISNULL(B.CHG_PRICE, 0) AS [SUM_CHG_PRICE]
			, ISNULL(B.DC_PRICE, 0) AS [SUM_DC_PRICE]
			, ISNULL(B.TAX_PRICE, 0) AS [SUM_TAX_PRICE]
			, ISNULL(B.PENALTY_PRICE, 0) AS [SUM_PENALTY_PRICE]
			/*
			,SUM(ISNULL(B.SALE_PRICE, 0)) AS [SUM_SALE_PRICE]
			,SUM(ISNULL(B.CHG_PRICE, 0)) AS [SUM_CHG_PRICE]
			,SUM(ISNULL(B.DC_PRICE, 0)) AS [SUM_DC_PRICE]
			,SUM(ISNULL(B.TAX_PRICE, 0)) AS [SUM_TAX_PRICE]
			,SUM(ISNULL(B.PENALTY_PRICE, 0)) AS [SUM_PENALTY_PRICE]
			*/
		,D.SIGN_CODE
	FROM RES_MASTER_DAMO A WITH(NOLOCK)
	INNER JOIN RES_CUSTOMER_DAMO B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE
	INNER JOIN CUS_CUSTOMER C WITH(NOLOCK) ON B.CUS_NO = C.CUS_NO
	INNER JOIN PKG_MASTER D WITH(NOLOCK) ON A.MASTER_CODE = D.MASTER_CODE
	WHERE 
	A.DEP_DATE >= @START_DATE 
		AND A.DEP_DATE < @END_DATE 
		AND A.RES_STATE <= 7 AND B.RES_STATE = 0
		AND B.BIRTH_DATE IS NOT NULL
		AND B.GENDER IS NOT NULL
)
, LIST_2 AS (
	SELECT
		 출발년도
		,CONVERT(INT, 연령대) AS 연령대
		,여행지역
		,SUM(CONVERT(BIGINT, 판매금액)) AS 판매금액
	FROM
	(
	SELECT
		 A.출발년도
		,CASE WHEN A.AGE IN ('7','8','9','10') THEN '7' ELSE A.AGE END AS 연령대
		,B.KOR_NAME AS [여행지역]
		,(SUM_SALE_PRICE - SUM_DC_PRICE + SUM_CHG_PRICE + SUM_TAX_PRICE + SUM_PENALTY_PRICE) AS 판매금액
		FROM LIST A
		LEFT JOIN PUB_REGION B WITH(NOLOCK) ON A.SIGN_CODE =B.SIGN
	) B
	GROUP BY B.출발년도,B.연령대,B.여행지역
)
SELECT 
	 출발년도,
	 CASE 
		WHEN 연령대 = 0 THEN '10대 미만'
		WHEN 연령대 = 7 THEN '70대 이상'
		ELSE CONVERT(VARCHAR(2), 연령대) + '0대' END AS 연령대,	 
	ISNULL([유럽], '0') AS [유럽],
	ISNULL([일본], '0') AS [일본],
	ISNULL([중국], '0') AS [중국],
	ISNULL([동남아], '0') AS [동남아]
FROM LIST_2
PIVOT
(
	MAX(판매금액)
	FOR 
	여행지역 IN ( [유럽],[일본],[중국],[동남아])
) PV
ORDER BY 출발년도, LEFT(연령대, 2) ASC
