


DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2018-01-01', @END_DATE = '2018-07-01';

WITH LIST AS 
( 
SELECT 
LEFT(CONVERT(VARCHAR(10),A.DEP_DATE,112),4) AS 출발년도
,CASE 
WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),@START_DATE)+1)=1 THEN '10세 미만'
WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),@START_DATE)+1)=3 THEN '100세 이상'
ELSE LEFT((DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE),@START_DATE)+1),1)
END AS AGE 
,ISNULL(ISNULL(B.GENDER,C.GENDER),'Z') AS [GENDER]
FROM RES_MASTER_DAMO A
INNER JOIN RES_CUSTOMER_DAMO B ON A.RES_CODE = B.RES_CODE
INNER JOIN CUS_CUSTOMER C ON B.CUS_NO = C.CUS_NO
INNER JOIN PKG_MASTER D ON A.MASTER_CODE = D.MASTER_CODE
WHERE 
A.DEP_DATE >= @START_DATE 
AND A.DEP_DATE < @END_DATE 
AND A.RES_STATE < 7 AND B.RES_STATE = 0
AND B.BIRTH_DATE IS NOT NULL
and b.gender is not null
)
SELECT
B.*
,COUNT(*) AS 인원
FROM
(
SELECT
A.출발년도
,A.GENDER AS [성별]
,CASE
WHEN A.AGE IN ('7','8','9','100세 이상') THEN '70대 이상'
ELSE A.AGE
END AS [연령대]
FROM LIST A
) B
GROUP BY B.출발년도,B.성별,B.연령대
ORDER BY B.출발년도,B.성별,B.연령대 ASC