-- 테이블 생성 --               
IF OBJECT_ID('TEMPDB..#CUS_LIST') IS NOT NULL               
 DROP TABLE #CUS_LIST;              
CREATE TABLE #CUS_LIST (F_CON DATETIME NOT NULL, L_CON DATETIME NOT NULL, DEP_YEAR INT NOT NULL, RES_NAME VARCHAR(40) NOT NULL, BIRTH_DATE DATETIME NOT NULL);               
ALTER TABLE #CUS_LIST ADD CONSTRAINT PKG_CUS_LIST2 PRIMARY KEY (F_CON, L_CON, DEP_YEAR, RES_NAME, BIRTH_DATE);               
           
-- 기준데이터 등록               
INSERT #CUS_LIST (F_CON, L_CON, DEP_YEAR, RES_NAME, BIRTH_DATE)               
SELECT               
 CONVERT(DATETIME, (CONVERT(VARCHAR(4), (YEAR(A.DEP_DATE)-2)) + '-01-01')) AS [F_CON],              
 CONVERT(DATETIME, (CONVERT(VARCHAR(4), (YEAR(A.DEP_DATE)+1)) + '-01-01')) AS [F_CON],              
 YEAR(A.DEP_DATE) AS [DEP_YEAR], A.RES_NAME, A.BIRTH_DATE --,COUNT(*) AS [COUNT]              
 FROM RES_MASTER_damo A WITH(NOLOCK)
 LEFT JOIN CUS_CUSTOMER B WITH(NOLOCK)
	ON A.CUS_NO = B.CUS_NO                  
WHERE A.DEP_DATE >= '2015-01-01' AND A.DEP_DATE < '2016-01-01' AND A.RES_STATE < 7                      
 AND A.PROFIT_TEAM_CODE <> 524 -- 법인고객 제외              
 AND A.CUS_NO > 3000              
 AND A.RES_NAME IS NOT NULL              
 AND A.BIRTH_DATE IS NOT NULL              
 AND A.CUS_NO NOT IN (SELECT AA.CUS_NO FROM TMP_TC_CUS_NO_INFO AA WITH(NOLOCK))              
 AND A.CUS_NO NOT IN (SELECT AA.CUS_NO FROM COM_EMPLOYEE_MATCHING AA WITH(NOLOCK))              
 AND A.RES_NAME NOT LIKE '%인솔자%' AND A.RES_NAME NOT LIKE '%가이드%'              
GROUP BY YEAR(A.DEP_DATE), A.RES_NAME, A.BIRTH_DATE               
ORDER BY YEAR(A.DEP_DATE), A.RES_NAME, A.BIRTH_DATE;      
               

               
WITH TEMP_LIST AS (               
 SELECT YEAR(A.DEP_DATE) AS [REST_YEAR], C.DEP_YEAR, A.RES_NAME, C.BIRTH_DATE, ROW_NUMBER() OVER (PARTITION BY C.DEP_YEAR, C.RES_NAME, C.BIRTH_DATE ORDER BY A.DEP_DATE) AS [ROW_NUM], RES_CODE
 FROM RES_MASTER_damo A WITH(NOLOCK)
 LEFT JOIN CUS_CUSTOMER B WITH(NOLOCK)
	ON A.CUS_NO = B.CUS_NO                   
 INNER JOIN #CUS_LIST C ON A.RES_NAME = C.RES_NAME AND A.BIRTH_DATE = C.BIRTH_DATE              
 WHERE A.DEP_DATE >= C.F_CON AND A.DEP_DATE < C.L_CON AND A.RES_STATE < 7 
  AND A.PROFIT_TEAM_CODE <> 524 -- 법인고객 제외             
  AND A.CUS_NO > 3000             
  AND A.RES_NAME IS NOT NULL             
  AND A.BIRTH_DATE IS NOT NULL             
  AND A.CUS_NO NOT IN (SELECT AA.CUS_NO FROM TMP_TC_CUS_NO_INFO AA WITH(NOLOCK))             
  AND A.CUS_NO NOT IN (SELECT AA.CUS_NO FROM COM_EMPLOYEE_MATCHING AA WITH(NOLOCK))             
  AND A.RES_NAME NOT LIKE '%인솔자%' AND A.RES_NAME NOT LIKE '%가이드%' AND A.RES_NAME NOT LIKE '%웹투어%' AND A.RES_NAME NOT LIKE '%본투어%'
)               
               
SELECT A.DEP_YEAR, A.ROW_NUM, COUNT(*) AS [CUS_LIST], RES_CODE
FROM TEMP_LIST A               
WHERE A.REST_YEAR = A.DEP_YEAR               
GROUP BY A.DEP_YEAR, A.ROW_NUM, RES_CODE        
ORDER BY A.DEP_YEAR, A.ROW_NUM

SELECT TOP 100 *
FROM #CUS_LIST