DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2016-01-01', @END_DATE = '2017-12-31';

WITH LIST AS
(
SELECT 
A.RES_CODE
,A.CXL_DATE
,A.DEP_DATE
,A.SIGN_CODE
,CONVERT(DECIMAL,SUM(A.PRICE)) AS [PRICE]
,DATEDIFF(DAY, A.CXL_DATE, A.DEP_DATE) AS [DATE_DIFF]
FROM (
		SELECT
		 B.CUS_NO
		,B.RES_CODE
		,A.DEP_DATE
		,A.CXL_DATE
		,D.SIGN_CODE
		,(CASE B.AGE_TYPE WHEN 0 THEN C.ADT_PRICE WHEN 1 THEN C.CHD_PRICE WHEN 2 THEN C.INF_PRICE END) AS [PRICE]
		,DATEDIFF(DAY, A.CXL_DATE, A.DEP_DATE)  AS [DATE_DIFF] 
		FROM RES_MASTER_damo A 
		INNER JOIN RES_CUSTOMER_damo B
			ON A.RES_CODE = B.RES_CODE 
		INNER JOIN PKG_DETAIL_PRICE C 
			ON A.PRO_CODE = C.PRO_CODE AND A.PRICE_SEQ = C.PRICE_SEQ
		INNER JOIN PKG_MASTER D
			ON A.MASTER_CODE = D.MASTER_CODE
		WHERE 
		A.RES_CODE IN ( 
			SELECT MIN(AA.RES_CODE)  -- 출발월 과 , 예약자고객번호 중에서 가장 처음예약한 예약번호 
			--,CONVERT(VARCHAR(7),AA.DEP_DATE,121) AS DEP_MONTH , AA.CUS_NO , MAX(AA.RES_CODE) , COUNT(AA.RES_CODE)
			FROM RES_MASTER_DAMO AA
			--INNER JOIN RES_CUSTOMER_DAMO B ON A.RES_CODE = B.RES_CODE
			WHERE AA.PRO_TYPE = 1  -- 패키지 예약중 
				AND AA.RES_STATE = 9 -- 취소건만   
				--AND B.RES_STATE <> 2  -- 이동아닌것 
				AND AA.CXL_DATE IS NOT NULL  -- 취소일이 있으면 
				AND AA.NEW_DATE >= @START_DATE AND AA.NEW_DATE < @END_DATE  -- 해당 예약일 
				AND AA.PROFIT_TEAM_CODE <> 524
				--AND D.SIGN_CODE = 'E'   -- ★ 지역별로 구분하여 뽑고자할 때 사용 조건 
			GROUP BY  CONVERT(VARCHAR(7),AA.DEP_DATE,121), AA.CUS_NO   -- 출발월 과 , 예약자고객번호로 그룹핑
				--HAVING COUNT (*) > 2 
				--ORDER BY CONVERT(VARCHAR(7),AA.DEP_DATE,121) ,  AA.CUS_NO 
			)   
		AND B.RES_STATE <> 2  --이동된 것 제외 
		--ORDER BY A.DEP_DATE  

		--검증쿼리 
		/*
		SELECT   
			 CONVERT(VARCHAR(7),AA.DEP_DATE,121) AS DEP_MONTH , AA.CUS_NO , AA.RES_CODE , AA.RES_CODE
		FROM RES_MASTER_DAMO AA
		--INNER JOIN RES_CUSTOMER_DAMO B ON A.RES_CODE = B.RES_CODE
		WHERE AA.PRO_TYPE = 1  -- 패키지 예약중 
		AND AA.RES_STATE = 9 -- 취소건만   
		--AND B.RES_STATE <> 2  -- 이동아닌것 
		AND AA.CXL_DATE IS NOT NULL  -- 취소일이 있으면 
		AND AA.NEW_DATE >= '2014-01-01' AND AA.NEW_DATE < '2015-01-01'  -- 해당 예약일 
		AND AA.DEP_DATE > '2014-01-01' AND  AA.DEP_DATE < '2014-02-01' 
		AND AA.CUS_NO = 3186631 */ 

	) A

GROUP BY A.RES_CODE, A.CUS_NO, A.CXL_DATE, A.DEP_DATE,A.SIGN_CODE

)

SELECT 

A.DATE_DIFF AS 취소시점
,A.SIGN_CODE
,COUNT(*) AS 인원수
,AVG(A.PRICE) AS [PRICE]
FROM LIST A
WHERE 
A.DATE_DIFF >=0 
AND A.DATE_DIFF < 91

GROUP BY A.DATE_DIFF,A.SIGN_CODE
ORDER BY A.DATE_DIFF,A.SIGN_CODE
