

-------------------------------------------- 유럽-----------------------------------------------
SELECT 
SIGN_CODE , 
PRICE_RANGE , SUM(ALL_CUS_CNT) 전체예약출발자수 ,SUM(CXL_CUS_CNT) 취소예약출발자수 ,
 ( CONVERT(DECIMAL(10,2),SUM(CXL_CUS_CNT))  / CONVERT(DECIMAL(10,2),SUM(ALL_CUS_CNT)) ) * 100.0  취소율
FROM 
(
SELECT 
	A.RES_CODE , 
	D.SIGN_CODE , 
	CASE 
		WHEN C.ADT_PRICE BETWEEN 1000000 AND 1399999 THEN '100만원~130만원대'
		WHEN C.ADT_PRICE BETWEEN 1400000 AND 1499999 THEN '140만원대' 
		WHEN C.ADT_PRICE BETWEEN 1500000 AND 1599999 THEN '150만원대' 
		WHEN C.ADT_PRICE BETWEEN 1600000 AND 1699999 THEN '160만원대'
		WHEN C.ADT_PRICE BETWEEN 1700000 AND 1799999 THEN '170만원대' 
		WHEN C.ADT_PRICE BETWEEN 1800000 AND 1899999 THEN '180만원대' 
		WHEN C.ADT_PRICE BETWEEN 1900000 AND 1999999 THEN '190만원대' 
		WHEN C.ADT_PRICE BETWEEN 2000000 AND 2099999 THEN '200만원대' 
		WHEN C.ADT_PRICE BETWEEN 2100000 AND 2199999 THEN '210만원대' 
		WHEN C.ADT_PRICE BETWEEN 2200000 AND 2299999 THEN '220만원대' 
		WHEN C.ADT_PRICE BETWEEN 2300000 AND 2399999 THEN '230만원대' 

		ELSE '240만원대 이상 ' END AS PRICE_RANGE  
		, C.ADT_PRICE 
		, A.RES_STATE , 
	--전체예약이 취소된건만 취소 출발자수(원래출발자수) + 살아있는 예약에서 취소된 출발자수 
	CASE WHEN A.RES_STATE IN (9) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ELSE 0 END
	+ 
	CASE WHEN A.RES_STATE NOT IN ( 7,8,9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE AND RES_STATE IN (1)) ELSE 0 END AS CXL_CUS_CNT ,
	--전체출발자수
	(SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ALL_CUS_CNT 
FROM RES_MASTER_damo A 
	INNER JOIN PKG_DETAIL B 
		ON A.PRO_CODE = B.PRO_CODE 
	INNER JOIN PKG_DETAIL_PRICE C  -- 가격 
		ON B.PRO_CODE = C.PRO_CODE 
		AND A.PRICE_SEQ = C.PRICE_SEQ 
	INNER JOIN PKG_MASTER D 
		ON A.MASTER_CODE = D.MASTER_CODE 
WHERE A.NEW_DATE >= '2016-01-01' 
AND A.NEW_DATE < '2017-12-31' 
AND SIGN_CODE = 'E'
)  T 

GROUP BY SIGN_CODE, PRICE_RANGE 
order by sign_code

-------------------------------------------- 동남아---------------------------------------------

SELECT 
SIGN_CODE , 
PRICE_RANGE , SUM(ALL_CUS_CNT) 전체예약출발자수 ,SUM(CXL_CUS_CNT) 취소예약출발자수 ,
 ( CONVERT(DECIMAL(10,2),SUM(CXL_CUS_CNT))  / CONVERT(DECIMAL(10,2),SUM(ALL_CUS_CNT)) ) * 100.0  취소율
FROM 
(
SELECT 
	A.RES_CODE , 
	D.SIGN_CODE , 
	CASE 
		WHEN C.ADT_PRICE BETWEEN 300000 AND 399999 THEN '30만원대'
		WHEN C.ADT_PRICE BETWEEN 400000 AND 499999 THEN '40만원대' 
		WHEN C.ADT_PRICE BETWEEN 500000 AND 599999 THEN '50만원대' 
		WHEN C.ADT_PRICE BETWEEN 600000 AND 699999 THEN '60만원대'
		WHEN C.ADT_PRICE BETWEEN 700000 AND 799999 THEN '70만원대' 
		WHEN C.ADT_PRICE BETWEEN 800000 AND 899999 THEN '80만원대' 
		WHEN C.ADT_PRICE BETWEEN 900000 AND 999999 THEN '90만원대' 
		WHEN C.ADT_PRICE BETWEEN 1000000 AND 1099999 THEN '100만원대' 
		ELSE '기타 ' END AS PRICE_RANGE  
		, C.ADT_PRICE 
		, A.RES_STATE , 
	--전체예약이 취소된건만 취소 출발자수(원래출발자수) + 살아있는 예약에서 취소된 출발자수 
	CASE WHEN A.RES_STATE IN ( 9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ELSE 0 END
	+ 
	CASE WHEN A.RES_STATE NOT IN ( 7,8,9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE AND RES_STATE IN (1) ) ELSE 0 END AS CXL_CUS_CNT ,
	--전체출발자수
	(SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ALL_CUS_CNT 
FROM RES_MASTER_damo A 
	INNER JOIN PKG_DETAIL B 
		ON A.PRO_CODE = B.PRO_CODE 
	INNER JOIN PKG_DETAIL_PRICE C  -- 가격 
		ON B.PRO_CODE = C.PRO_CODE 
		AND A.PRICE_SEQ = C.PRICE_SEQ 
	INNER JOIN PKG_MASTER D 
		ON A.MASTER_CODE = D.MASTER_CODE 
WHERE A.NEW_DATE >= '2016-01-01' 
AND A.NEW_DATE < '2017-12-31' 
AND SIGN_CODE = 'A'
)  T 

GROUP BY SIGN_CODE, PRICE_RANGE 

---------------------------------------- 중국----------------------------------------------------

SELECT 
SIGN_CODE , 
PRICE_RANGE , SUM(ALL_CUS_CNT) 전체예약출발자수 ,SUM(CXL_CUS_CNT) 취소예약출발자수 ,
 ( CONVERT(DECIMAL(10,2),SUM(CXL_CUS_CNT))  / CONVERT(DECIMAL(10,2),SUM(ALL_CUS_CNT)) ) * 100.0  취소율
FROM 
(
SELECT 
	A.RES_CODE , 
	D.SIGN_CODE , 
	CASE 
		WHEN C.ADT_PRICE BETWEEN 300000 AND 399999 THEN '30만원대'
		WHEN C.ADT_PRICE BETWEEN 400000 AND 499999 THEN '40만원대' 
		WHEN C.ADT_PRICE BETWEEN 500000 AND 599999 THEN '50만원대' 
		WHEN C.ADT_PRICE BETWEEN 600000 AND 699999 THEN '60만원대'
		WHEN C.ADT_PRICE BETWEEN 700000 AND 799999 THEN '70만원대' 
		WHEN C.ADT_PRICE BETWEEN 800000 AND 899999 THEN '80만원대' 
		WHEN C.ADT_PRICE BETWEEN 900000 AND 999999 THEN '90만원대' 
		WHEN C.ADT_PRICE BETWEEN 1000000 AND 1099999 THEN '100만원대' 
		ELSE '기타 ' END AS PRICE_RANGE  
		, C.ADT_PRICE 
		, A.RES_STATE , 
	--전체예약이 취소된건만 취소 출발자수(원래출발자수) + 살아있는 예약에서 취소된 출발자수 
	CASE WHEN A.RES_STATE IN ( 9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ELSE 0 END
	+ 
	CASE WHEN A.RES_STATE NOT IN ( 7,8,9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE AND RES_STATE IN (1) ) ELSE 0 END AS CXL_CUS_CNT ,
	--전체출발자수
	(SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ALL_CUS_CNT 
FROM RES_MASTER_damo A 
	INNER JOIN PKG_DETAIL B 
		ON A.PRO_CODE = B.PRO_CODE 
	INNER JOIN PKG_DETAIL_PRICE C  -- 가격 
		ON B.PRO_CODE = C.PRO_CODE 
		AND A.PRICE_SEQ = C.PRICE_SEQ 
	INNER JOIN PKG_MASTER D 
		ON A.MASTER_CODE = D.MASTER_CODE 
WHERE A.NEW_DATE >= '2016-01-01' 
AND A.NEW_DATE < '2017-12-31' 
AND SIGN_CODE = 'C'
)  T 

GROUP BY SIGN_CODE, PRICE_RANGE 

------------------------------------------------------------------ 일본 -----------------

SELECT 
SIGN_CODE , 
PRICE_RANGE , SUM(ALL_CUS_CNT) 전체예약출발자수 ,SUM(CXL_CUS_CNT) 취소예약출발자수 ,
 ( CONVERT(DECIMAL(10,2),SUM(CXL_CUS_CNT))  / CONVERT(DECIMAL(10,2),SUM(ALL_CUS_CNT)) ) * 100.0  취소율
FROM 
(
SELECT 
	A.RES_CODE , 
	D.SIGN_CODE , 
	CASE 
		WHEN C.ADT_PRICE BETWEEN 300000 AND 399999 THEN '30만원대'
		WHEN C.ADT_PRICE BETWEEN 400000 AND 499999 THEN '40만원대' 
		WHEN C.ADT_PRICE BETWEEN 500000 AND 599999 THEN '50만원대' 
		WHEN C.ADT_PRICE BETWEEN 600000 AND 699999 THEN '60만원대'
		WHEN C.ADT_PRICE BETWEEN 700000 AND 799999 THEN '70만원대' 
		WHEN C.ADT_PRICE BETWEEN 800000 AND 899999 THEN '80만원대' 
		WHEN C.ADT_PRICE BETWEEN 900000 AND 999999 THEN '90만원대' 
		WHEN C.ADT_PRICE BETWEEN 1000000 AND 1099999 THEN '100만원대' 
		ELSE '기타 ' END AS PRICE_RANGE  
		, C.ADT_PRICE 
		, A.RES_STATE , 
	--전체예약이 취소된건만 취소 출발자수(원래출발자수) + 살아있는 예약에서 취소된 출발자수 
	CASE WHEN A.RES_STATE IN ( 9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ELSE 0 END
	+ 
	CASE WHEN A.RES_STATE NOT IN ( 7,8,9 ) THEN (SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE AND RES_STATE IN (1) ) ELSE 0 END AS CXL_CUS_CNT ,
	--전체출발자수
	(SELECT COUNT(*) FROM RES_CUSTOMER_DAMO WHERE RES_CODE = A.RES_CODE ) ALL_CUS_CNT 
FROM RES_MASTER_damo A 
	INNER JOIN PKG_DETAIL B 
		ON A.PRO_CODE = B.PRO_CODE 
	INNER JOIN PKG_DETAIL_PRICE C  -- 가격 
		ON B.PRO_CODE = C.PRO_CODE 
		AND A.PRICE_SEQ = C.PRICE_SEQ 
	INNER JOIN PKG_MASTER D 
		ON A.MASTER_CODE = D.MASTER_CODE 
WHERE A.NEW_DATE >= '2016-01-01' 
AND A.NEW_DATE < '2017-12-31' 
AND SIGN_CODE = 'J'
)  T 

GROUP BY SIGN_CODE, PRICE_RANGE 
