DECLARE @START_DATE DATETIME, @END_DATE DATETIME		
SELECT @START_DATE = '2017-01-01', @END_DATE = '2018-01-01'; 		
		
WITH LIST AS		
(		
	SELECT 	
	LEFT(CONVERT(VARCHAR(10),A.DEP_DATE,112),4) AS 출발년도	
	,ISNULL(ISNULL(A.GENDER,B.GENDER),'Z') AS [GENDER]	
	,CASE WHEN LEN(DATEDIFF(YEAR,ISNULL(A.BIRTH_DATE,B.BIRTH_DATE),@START_DATE)+1)=1 THEN '10세 미만'	
		  WHEN LEN(DATEDIFF(YEAR,ISNULL(A.BIRTH_DATE,B.BIRTH_DATE),@START_DATE)+1)=3 THEN '100세 이상'
		  ELSE LEFT((DATEDIFF(YEAR,ISNULL(A.BIRTH_DATE,B.BIRTH_DATE),@START_DATE)+1),1)
		  END AS AGE 
	FROM RES_MASTER_DAMO A WITH(NOLOCK)
	LEFT JOIN CUS_CUSTOMER_DAMO B WITH(NOLOCK) ON A.CUS_NO = B.CUS_NO
	WHERE A.DEP_DATE >= @START_DATE AND A.DEP_DATE < @END_DATE AND A.RES_STATE NOT IN (7,8,9)
	AND NOT EXISTS (SELECT * FROM RES_CUSTOMER_DAMO WITH(NOLOCK) WHERE RES_CODE = A.RES_CODE AND CUS_NAME = A.RES_NAME AND RES_STATE = 0)
	AND A.CUS_NO > 1	
)		
		
SELECT B.출발년도, B.연령대		
,COUNT(*) AS [인원수]		
FROM		
(		
SELECT 		
A.출발년도		
,case		
WHEN A.AGE IN ('7','8','9','100세 이상') THEN '70대 이상'		
ELSE A.AGE		
END AS [연령대]		
FROM LIST A		
) B		
GROUP BY B.출발년도, B.연령대		
ORDER BY B.출발년도, B.연령대 ASC; 		
