-- 도시별 인기상품 -- 도시 조회--
SELECT RM.MASTER_CODE, PM.MASTER_NAME, COUNT(RC.RES_CODE) AS DEP_CUS_CNT, PMP.ALONE_PERCENT, PMP.COUPLE_PERCENT, PMP.FAMILY_PERCENT, PMP.FRIEND_PERCENT, PMP.MEETING_PERCENT, PMP.ETC_PERCENT, PMP.TOTAL_COUNT
FROM RES_MASTER_DAMO RM WITH(NOLOCK)
INNER JOIN RES_CUSTOMER_damo RC WITH(NOLOCK)
	ON RM.RES_CODE = RC.RES_CODE
INNER JOIN PKG_MASTER PM WITH(NOLOCK)
	ON RM.MASTER_CODE = PM.MASTER_CODE
INNER JOIN PKG_DETAIL PD WITH(NOLOCK)
	ON RM.PRO_CODE = PD.PRO_CODE
LEFT JOIN PRO_TRANS_SEAT PT WITH(NOLOCK)
	ON PD.SEAT_CODE = PT.SEAT_CODE
LEFT JOIN PUB_AIRPORT PA WITH(NOLOCK)
	ON PT.DEP_ARR_AIRPORT_CODE = PA.AIRPORT_CODE
LEFT JOIN PUB_CITY PC WITH(NOLOCK)
	ON PA.CITY_CODE = PC.CITY_CODE
LEFT JOIN PKG_MASTER_PARTNER PMP WITH(NOLOCK)
	ON PM.MASTER_CODE = PMP.MASTER_CODE
WHERE RM.RES_STATE < 7 AND RC.RES_STATE = 0
AND RM.DEP_DATE >= '2019-01-01' AND RM.DEP_DATE < '2020-01-01'
AND PC.KOR_NAME = '나트랑'
GROUP BY RM.MASTER_CODE, PM.MASTER_NAME, PMP.ALONE_PERCENT, PMP.COUPLE_PERCENT, PMP.FAMILY_PERCENT, PMP.FRIEND_PERCENT, PMP.MEETING_PERCENT, PMP.ETC_PERCENT, PMP.TOTAL_COUNT
ORDER BY PMP.COUPLE_PERCENT DESC


-- 도시별 마스터별 인기상품 -- 도시 전체 통틀어서 순위 출발자순으로 리스트업 --
SELECT PC.KOR_NAME, RM.MASTER_CODE, PM.MASTER_NAME, COUNT(RC.RES_CODE) AS DEP_CUS_CNT
FROM RES_MASTER_DAMO RM WITH(NOLOCK)
INNER JOIN RES_CUSTOMER_damo RC WITH(NOLOCK)
	ON RM.RES_CODE = RC.RES_CODE
INNER JOIN PKG_MASTER PM WITH(NOLOCK)
	ON RM.MASTER_CODE = PM.MASTER_CODE
INNER JOIN PKG_DETAIL PD WITH(NOLOCK)
	ON RM.PRO_CODE = PD.PRO_CODE
LEFT JOIN PRO_TRANS_SEAT PT WITH(NOLOCK)
	ON PD.SEAT_CODE = PT.SEAT_CODE
LEFT JOIN PUB_AIRPORT PA WITH(NOLOCK)
	ON PT.DEP_ARR_AIRPORT_CODE = PA.AIRPORT_CODE
LEFT JOIN PUB_CITY PC WITH(NOLOCK)
	ON PA.CITY_CODE = PC.CITY_CODE
WHERE RM.RES_STATE < 7 AND RC.RES_STATE = 0
AND RM.DEP_DATE >= '2019-01-01' AND RM.DEP_DATE < '2020-01-01' AND PC.KOR_NAME IS NOT NULL
GROUP BY RM.MASTER_CODE, PM.MASTER_NAME, PC.KOR_NAME
ORDER BY DEP_CUS_CNT DESC


-- 도시별 인기 예약 도시 전체 리스트업 --
SELECT  COUNT(RC.RES_CODE) AS DEP_CUS_CNT ,PM.MASTER_CODE, PM.MASTER_NAME
--,PC.KOR_NAME --도시별 출발자수
FROM RES_MASTER_DAMO RM WITH(NOLOCK)
INNER JOIN RES_CUSTOMER_damo RC WITH(NOLOCK)
	ON RM.RES_CODE = RC.RES_CODE
INNER JOIN PKG_MASTER PM WITH(NOLOCK)
	ON RM.MASTER_CODE = PM.MASTER_CODE
INNER JOIN PKG_DETAIL PD WITH(NOLOCK)
	ON RM.PRO_CODE = PD.PRO_CODE
LEFT JOIN PRO_TRANS_SEAT PT WITH(NOLOCK)
	ON PD.SEAT_CODE = PT.SEAT_CODE
LEFT JOIN PUB_AIRPORT PA WITH(NOLOCK)
	ON PT.DEP_ARR_AIRPORT_CODE = PA.AIRPORT_CODE
LEFT JOIN PUB_CITY PC WITH(NOLOCK)
	ON PA.CITY_CODE = PC.CITY_CODE
LEFT JOIN PUB_NATION PN WITH(NOLOCK)
	ON PC.NATION_CODE = PN.NATION_CODE
WHERE RM.RES_STATE < 7 AND RC.RES_STATE = 0
AND RM.DEP_DATE >= '2019-01-01' AND RM.DEP_DATE < '2020-01-01' AND PC.KOR_NAME = '깔리보' --AND PN.KOR_NAME = '독일'
GROUP BY PM.MASTER_CODE, PM.MASTER_NAME
--PC.KOR_NAME
ORDER BY DEP_CUS_CNT DESC

SELECT TOP 100 *
FROM RES_MASTER_DAMO RM WITH(NOLOCK)
INNER JOIN RES_CUSTOMER_DAMO RC WITH(NOLOCK)
	ON RM.RES_CODE = RC.RES_CODE
INNER JOIN PKG_MASTER PM WITH(NOLOCK)
	ON PM.MASTER_CODE = RM.MASTER_CODE
INNER JOIN PKG_DETAIL PD WITH(NOLOCK)
	ON RM.PRO_CODE = PD.PRO_CODE
LEFT JOIN PRo_TRANS_SEAT PT WITH(NOLOCK)
	ON 


WHERE RM.RES_STATE < 7 AND RC.RES_STATE = 0
AND RM.DEP_DATE >= '2019-01-01' AND RM.DEP_DATE < '2020-01-01'

select top 100 *
from pub_airport
where city_code = 'klo'

select top 100 *
from PUB_CITY
where city_code = 'klo'

