
--도시별 인기상품 리스트 및 국가별 인기상품 리스트 조회 쿼리 -- 변경하여 사용 pc랑 pn
SELECT  COUNT(RC.RES_CODE) AS DEP_CUS_CNT ,PM.MASTER_CODE, PM.MASTER_NAME
--,PC.KOR_NAME --도시별 출발자수
FROM RES_MASTER_DAMO RM WITH(NOLOCK)
INNER JOIN RES_CUSTOMER_damo RC WITH(NOLOCK)
	ON RM.RES_CODE = RC.RES_CODE
INNER JOIN PKG_MASTER PM WITH(NOLOCK)
	ON RM.MASTER_CODE = PM.MASTER_CODE
INNER JOIN PKG_DETAIL PD WITH(NOLOCK)
	ON RM.PRO_CODE = PD.PRO_CODE
LEFT JOIN PRO_TRANS_SEAT PT WITH(NOLOCK)
	ON PD.SEAT_CODE = PT.SEAT_CODE
LEFT JOIN PUB_AIRPORT PA WITH(NOLOCK)
	ON PT.DEP_ARR_AIRPORT_CODE = PA.AIRPORT_CODE
LEFT JOIN PUB_CITY PC WITH(NOLOCK)
	ON PA.CITY_CODE = PC.CITY_CODE
LEFT JOIN PUB_NATION PN WITH(NOLOCK)
	ON PC.NATION_CODE = PN.NATION_CODE
WHERE RM.RES_STATE < 7 AND RC.RES_STATE = 0
AND RM.DEP_DATE >= '2019-01-01' AND RM.DEP_DATE < '2020-01-01' AND PC.KOR_NAME = '깔리보' --AND PN.KOR_NAME = '독일'
GROUP BY PM.MASTER_CODE, PM.MASTER_NAME
--PC.KOR_NAME
ORDER BY DEP_CUS_CNT DESC