
-- 예시... 유럽, 동남아 등 큰 지역 출발자 비중을 다른 쿼리로 뽑고 난후 --
-- 상승하고 있는 지역중 상세 인기 국가 및 도시를 뽑기위해 쿼리를 지속적으로 밑에 WHERE 조건을 변경하면서 진행 --
-- 대한민국 이런게 나올수도 있는데 해당 상품은 조회 해본 결과 APIC 마스터 코드상품과 같은 경우인게 많은데
-- 해당상품은 모든 전지역 상품을 모아놓은거라 BEST상품을 각 행사별로 다 넣어놓은 종합 기획전 같은 상품 --
SELECT PC.KOR_NAME, PM.MASTER_CODE, COUNT(RC.RES_CODE)			
FROM RES_MASTER_DAMO RM WITH(NOLOCK)			
INNER JOIN RES_CUSTOMER_DAMO RC WITH(NOLOCK)			
	ON RM.RES_CODE = RC.RES_CODE		
INNER JOIN PKG_MASTER PM WITH(NOLOCK)			
	ON RM.MASTER_CODE = PM.MASTER_CODE		
INNER JOIN PKG_DETAIL PD WITH(NOLOCK)			
	ON RM.PRO_CODE = PD.PRO_CODE		
INNER JOIN PRO_TRANS_SEAT PTS WITH(NOLOCK)			
	ON  PD.SEAT_CODE = PTS.SEAT_CODE		
LEFT JOIN PUB_AIRPORT PA WITH(NOLOCK)			
	ON PTS.DEP_ARR_AIRPORT_CODE = PA.AIRPORT_CODE		
LEFT JOIN PUB_CITY PC WITH(NOLOCK)			
	ON PA.CITY_CODE = PC.CITY_CODE		
LEFT JOIN PUB_NATION PN WITH(NOLOCK)			
	ON PC.NATION_CODE = PN.NATION_CODE		
WHERE RM.PRO_CODE LIKE 'E%' AND RM.DEP_DATE >= '2019-02-01' AND RM.DEP_DATE < '2019-06-01' AND PN.KOR_NAME = '독일' AND PC.KOR_NAME = '프랑크푸르트'			
AND RM.RES_STATE < 7 AND RC.RES_STATE = 0			
GROUP BY PC.KOR_NAME, PM.MASTER_CODE			
ORDER BY COUNT(RC.RES_CODE) DESC			
