SELECT * FROM
(
	SELECT
	SIGN_NAME, MASTER_CODE, MASTER_NAME,
	DENSE_RANK() OVER (PARTITION BY SIGN_NAME ORDER BY DEP_CUS_CNT DESC) AS DEP_RANK, -- 지역별로 출발자수 많은순으로 DESC 순번매김
	DEP_CUS_CNT
	FROM
	(
		SELECT PR.KOR_NAME AS SIGN_NAME,
		RM.MASTER_CODE,
		PM.MASTER_NAME,
		COUNT(RC.RES_CODE) AS DEP_CUS_CNT
		FROM RES_MASTER_DAMO RM WITH(NOLOCK)
			INNER JOIN RES_CUSTOMER_DAMO RC WITH(NOLOCK)
				ON RM.RES_CODE = RC.RES_CODE
			INNER JOIN PKG_DETAIL PD WITH(NOLOCK)
				ON RM.PRO_CODE = PD.PRO_CODE
			INNER JOIN PKG_MASTER PM WITH(NOLOCK)
				ON PD.MASTER_CODE = PM.MASTER_CODE
			LEFT JOIN PUB_REGION PR WITH(NOLOCK)
				ON PM.SIGN_CODE = PR.SIGN
		WHERE RM.DEP_DATE >= '2018-11-01' AND RM.DEP_DATE < '2019-03-01' -- 기간
			  AND RM.RES_STATE < 7 -- 취소 환불 이동 제외
			  AND RC.RES_STATE = 0
			  AND RM.PROVIDER <> '33' --BTMS 제외
			  AND PR.KOR_NAME <> '전지역'
			  AND RM.PRO_TYPE = 1
		GROUP BY PR.KOR_NAME, RM.MASTER_CODE, PM.MASTER_NAME --지역별, 마스터별, 행사이름별 GROUP BY
	)TBL
)TT
WHERE DEP_RANK <=5
ORDER BY SIGN_NAME DESC