DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SELECT @START_DATE = '2018-11-01', @END_DATE = '2019-03-01'
-- 지역 정보
DECLARE @REGION_NAME_LIST VARCHAR(300);
SELECT @REGION_NAME_LIST = STUFF((SELECT ',[' + KOR_NAME + ']' AS [text()] FROM PUB_REGION WITH(NOLOCK) FOR XML PATH('')), 1, 1, ''); 

WITH LIST AS 
( 
 SELECT 
  CASE 
   WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1) = 1 THEN '0'
   WHEN LEN(DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1) = 3 THEN '10'
   ELSE LEFT((DATEDIFF(YEAR,ISNULL(B.BIRTH_DATE,C.BIRTH_DATE), A.DEP_DATE) + 1),1) END AS AGE 
  ,ISNULL(B.GENDER,C.GENDER) AS [GENDER]
  ,D.SIGN_CODE
 FROM RES_MASTER_DAMO A WITH(NOLOCK)
 INNER JOIN RES_CUSTOMER_DAMO B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE
 INNER JOIN CUS_CUSTOMER_DAMO C WITH(NOLOCK) ON B.CUS_NO = C.CUS_NO
 INNER JOIN PKG_MASTER D WITH(NOLOCK) ON A.MASTER_CODE = D.MASTER_CODE
 WHERE 
 A.DEP_DATE >= @START_DATE 
  AND A.DEP_DATE < @END_DATE 
  AND A.RES_STATE < 7 AND B.RES_STATE = 0
  AND B.BIRTH_DATE IS NOT NULL
  AND B.GENDER IS NOT NULL
)
, LIST_2 AS (
 SELECT
여행지역
  ,COUNT(*) AS 인원
  ,[성별]
 FROM
 (
 SELECT
  A.GENDER AS [성별]
  ,B.KOR_NAME AS [여행지역]
  FROM LIST A
  LEFT JOIN PUB_REGION B WITH(NOLOCK) ON A.SIGN_CODE =B.SIGN
 ) B
 GROUP BY B.성별,B.여행지역
)
SELECT
  [성별],
 ISNULL([북미지역], '0') AS [북미지역],
 ISNULL([중미지역], '0') AS [중미지역],
 ISNULL([남미지역], '0') AS [남미지역],
 ISNULL([유럽], '0') AS [유럽],
 ISNULL([중동지역], '0') AS [중동지역],
 ISNULL([아프리카], '0') AS [아프리카],
 ISNULL([국내], '0') AS [국내],
 ISNULL([일본], '0') AS [일본],
 ISNULL([중국], '0') AS [중국],
 ISNULL([동남아], '0') AS [동남아],
 ISNULL([대양주], '0') AS [대양주],
 ISNULL([서인도], '0') AS [서인도],
 ISNULL([사이판/괌], '0') AS[사이판/괌],
 ISNULL([극동지역], '0') AS [극동지역],
 ISNULL([기타지역], '0') AS [기타지역]
FROM LIST_2
PIVOT
(
 SUM(인원)
 FOR 
 여행지역 IN ( [북미지역],[중미지역],[남미지역],[유럽],[중동지역],[아프리카],[국내],[일본],[중국],[동남아],[대양주],[서인도],[사이판/괌],[극동지역],[기타지역] )
) PV
ORDER BY [성별] ASC



-- 지역 코드 리스트 --
SELECT SIGN_CODE, KOR_NAME
FROM PKG_MASTER PM WITH(NOLOCK)
INNER JOIN PUB_REGION PR WITH(NOLOCK)
	ON PM.SIGN_CODE = PR.SIGN
GROUP BY SIGN_CODE, KOR_NAME


--RES_STAET 7은 환불 
SELECT TOP 100 *
FROM RES_MASTER_DAMO RM WITH(NOLOCK)
WHERE RM.RES_STATE = 6 AND RM.DEP_DATE >= '2019-11-01' AND + RM.DEP_DATE < '2019-12-01'