-- 테이블 생성
	CREATE TABLE [dbo].[PKG_MASTER_PARTNER_DATA_TEST](
	[PRO_CODE] [dbo].[PRO_CODE] NOT NULL,
	[MASTER_CODE] [dbo].[MASTER_CODE] NULL,
	[DEP_DATE] [date] NULL,
	[ALONE] [int] NULL,
	[FRIEND] [int] NULL,
	[FAMILY] [int] NULL,
	[COUPLE] [int] NULL,
	[MEETING] [int] NULL,
	[ETC] [int] NULL,
 CONSTRAINT [PK_PKG_MASTER_PARTNER_DATA_TEST] PRIMARY KEY CLUSTERED 
(
	[PRO_CODE] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

-- 테이블 생성
CREATE TABLE [dbo].[PKG_MASTER_PARTNER_TEST](
	[MASTER_CODE] [varchar](10) NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[ALONE] [int] NULL,
	[FRIEND] [int] NULL,
	[FAMILY] [int] NULL,
	[COUPLE] [int] NULL,
	[MEETING] [int] NULL,
	[ETC] [int] NULL,
	[ALONE_PERCENT] [int] NULL,
	[FRIEND_PERCENT] [int] NULL,
	[FAMILY_PERCENT] [int] NULL,
	[COUPLE_PERCENT] [int] NULL,
	[MEETING_PERCENT] [int] NULL,
	[ETC_PERCENT] [int] NULL,
	[TOTAL_COUNT] [int] NULL,
 CONSTRAINT [PK_PKG_MASTER_PARTNER_TEST] PRIMARY KEY CLUSTERED 
(
	[MASTER_CODE] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

--TRUNCATE TABLE PKG_MASTER_PARTNER_DATA_TEST
--TRUNCATE TABLE PKG_MASTER_PARTNER_TEST


DECLARE @PARTNER_LIST_TEST_1 TABLE (PRO_CODE PRO_CODE PRIMARY KEY, MASTER_CODE MASTER_CODE, DEP_DATE DATE, ALONE INT, FRIEND INT, FAMILY INT, COUPLE INT, MEETING INT, ETC INT)

	INSERT INTO @PARTNER_LIST_TEST_1
	SELECT PIV.PRO_CODE, PIV.MASTER_CODE, PIV.DEP_DATE, ISNULL(PIV.ALONE, 0), ISNULL(PIV.FRIEND, 0), ISNULL(PIV.FAMILY, 0), ISNULL(PIV.COUPLE, 0), ISNULL(PIV.MEETING, 0), ISNULL(PIV.ETC, 0)
	FROM (

		SELECT
			S.PRO_CODE, 
			S.MASTER_CODE,
			S.DEP_DATE,
			S.TOUR_TYPE AS [ATOUR_TYPE],
			COUNT(*) AS [ATOUR_COUNT]
		FROM (

			SELECT
				P.*,
				(
					CASE 										
						WHEN P.출발인원 = 1													THEN 'ALONE'
						WHEN P.출발인원 = 2 AND P.연령차 <=2 AND (P.남성 = 2 OR P.여성 = 2)	THEN 'FRIEND'
						WHEN P.예약팀내최저연령 <= 12 OR P.연령차 >= 20						THEN 'FAMILY'
						WHEN P.출발인원 % 2 = 0 AND P.출발인원 / 2 = P.남성					THEN 'COUPLE'
						WHEN P.출발인원 >= 3													THEN 'MEETING'
						ELSE 'ETC'
					END
				) AS [TOUR_TYPE]
			FROM (									

				SELECT 										
					A2.MASTER_CODE,
					A2.PRO_CODE,
					A2.RES_CODE,
					MAX(A2.DEP_DATE) AS [DEP_DATE],				
					COUNT(*) AS [출발인원],
					MAX(A2.출발자나이) AS [예약팀최고연령],
					MIN(A2.출발자나이) AS [예약팀내최저연령],
					(MAX(A2.출발자나이) - MIN(A2.출발자나이)) AS [연령차],
					SUM(CASE WHEN A2.출발자성별 = 'F' THEN 1 ELSE 0 END) AS '여성',									
					SUM(CASE WHEN A2.출발자성별 = 'M' THEN 1 ELSE 0 END) AS '남성'								
				FROM (

					SELECT 						
						A.MASTER_CODE,					
						A.PRO_CODE,					
						A.RES_CODE,					
						A.GENDER AS [예약자성별],
						DATEDIFF(YEAR,A.BIRTH_DATE,A.DEP_DATE) + 1 AS [예약자나이],
						B.CUS_NO AS [출발자고객번호],
						DATEDIFF(YEAR,B.BIRTH_DATE,A.DEP_DATE) + 1 AS [출발자나이],
						B.GENDER AS [출발자성별],
						A.DEP_DATE
					FROM RES_MASTER_damo A WITH(NOLOCK)
					INNER JOIN RES_CUSTOMER_damo B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE
					WHERE
						A.DEP_DATE >= '2019-03-01'
						AND A.DEP_DATE < '2019-04-01'
						AND A.RES_STATE < 7			
						AND B.RES_STATE = 0					
						AND B.BIRTH_DATE IS NOT NULL					
						AND B.SALE_PRICE <> 0					
						AND A.PRO_TYPE = 1					
				) A2									
				GROUP BY									
					A2.MASTER_CODE,
					A2.PRO_CODE,								
					A2.RES_CODE
			) P

		) S													
		GROUP BY S.MASTER_CODE, S.PRO_CODE, S.DEP_DATE, S.TOUR_TYPE

	) DDD
	PIVOT
	(
		max(DDD.ATOUR_COUNT)
		for DDD.ATOUR_TYPE in ([ALONE], [FRIEND], [FAMILY], [COUPLE], [MEETING], [ETC])
	) piv
	ORDER BY PIV.MASTER_CODE;
	
				
	--해당 데이터 추가
    INSERT INTO PKG_MASTER_PARTNER_DATA_TEST (PRO_CODE, MASTER_CODE, DEP_DATE, ALONE, FRIEND, FAMILY, COUPLE, MEETING, ETC)
	SELECT A.PRO_CODE, A.MASTER_CODE, A.DEP_DATE, A.ALONE, A.FRIEND, A.FAMILY, A.COUPLE, A.MEETING, A.ETC
	FROM @PARTNER_LIST_TEST_1 A
	LEFT JOIN PKG_MASTER_PARTNER_DATA_TEST B ON A.PRO_CODE = B.PRO_CODE
	WHERE B.PRO_CODE IS NULL;

    -- PKG_MASTER_PARTNER 데이터 생성
	DECLARE @MASTER_LIST_TEST_1 TABLE (MASTER_CODE MASTER_CODE PRIMARY KEY, DEP_DATE DATE, ALONE INT, FRIEND INT, FAMILY INT, COUPLE INT, MEETING INT, ETC INT, TOTAL INT);

	INSERT INTO @MASTER_LIST_TEST_1
	SELECT
		A.MASTER_CODE, MAX(A.DEP_DATE) AS [DEP_DATE], SUM(ALONE) AS [ALONE], SUM(FRIEND) AS [FRIEND], SUM(FAMILY) AS [FAMILY], SUM(COUPLE) AS [COUPLE], SUM(MEETING) AS [MEETING], SUM(ETC) AS [ETC]
		, SUM(ALONE + FRIEND + FAMILY + COUPLE + MEETING + ETC) AS [TOTAL]
	FROM PKG_MASTER_PARTNER_DATA_TEST A WITH(NOLOCK)
	WHERE DEP_DATE >= DATEADD(YY, -1, GETDATE())
	GROUP BY A.MASTER_CODE;

	
	INSERT INTO PKG_MASTER_PARTNER_TEST (MASTER_CODE, NEW_DATE, ALONE, FRIEND, FAMILY, COUPLE, MEETING, ETC, TOTAL_COUNT, ALONE_PERCENT, FRIEND_PERCENT, FAMILY_PERCENT, COUPLE_PERCENT, MEETING_PERCENT, ETC_PERCENT)
	SELECT A.MASTER_CODE, A.DEP_DATE, A.ALONE, A.FRIEND, A.FAMILY, A.COUPLE, A.MEETING, A.ETC, A.TOTAL
		, (A.ALONE * 100 / A.TOTAL)
		, (A.FRIEND * 100 / A.TOTAL)
		, (A.FAMILY * 100 / A.TOTAL)
		, (A.COUPLE * 100 / A.TOTAL)
		, (A.MEETING * 100 / A.TOTAL)
		, (A.ETC * 100 / A.TOTAL)
	FROM @MASTER_LIST_TEST_1 A
	LEFT JOIN PKG_MASTER_PARTNER_TEST B ON A.MASTER_CODE = B.MASTER_CODE
	WHERE B.MASTER_CODE IS NULL AND A.TOTAL >= 15;

	-- 완성된거 조회
	SELECT  *
	FROM PKG_MASTER_PARTNER_TEST
	ORDER BY ALONE_PERCENT DESC


SP_APP_ANALISYS_AGE_MASTER
SP_APP_ANALISYS_PARTNER_MASTER