SELECT G.*
FROM RES_MASTER_damo G
INNER JOIN RES_CUSTOMER_damo F WITH(NOLOCK) ON F.RES_CODE = G.RES_CODE
INNER JOIN CUS_CUSTOMER_DAMO E ON F.CUS_NO = E.CUS_NO
INNER JOIN PKG_DETAIL_SCH_CITY B ON G.PRO_CODE = B.PRO_CODE AND B.MAINCITY_YN = 'Y'
INNER JOIN PUB_CITY C WITH(NOLOCK) ON B.CITY_CODE = C.CITY_CODE
INNER JOIN PUB_NATION D WITH(NOLOCK) ON C.NATION_CODE = D.NATION_CODE
WHERE  G.RES_STATE <=7  AND F.RES_STATE =0
		AND G.DEP_DATE >= '2015-01-01' AND G.DEP_DATE < '2016-01-01'
		AND D.NATION_CODE = 'LA'



		SELECT
	A.*
	,MONTH(A.DEP_DATE) AS [DEP_MONTH]
	,MONTH(A.NEW_DATE) AS [NEW_MONTH]
	, (
		CASE
			WHEN A.BIRTH_DATE >= '1989-01-01' AND A.BIRTH_DATE < '1999-01-01' THEN '20'
			WHEN A.BIRTH_DATE >= '1969-01-01' AND A.BIRTH_DATE < '1989-01-01' THEN '3040'
			WHEN A.BIRTH_DATE >= '1949-01-01' AND A.BIRTH_DATE < '1969-01-01' THEN '5060'
			WHEN A.BIRTH_DATE >= '1939-01-01' AND A.BIRTH_DATE < '1949-01-01' THEN '70'
		END
	) AS [AGE]
FROM (
		SELECT 
			LEFT(CONVERT(VARCHAR(10),A.DEP_DATE,112),4) AS 출발년도
			, ISNULL(B.BIRTH_DATE,C.BIRTH_DATE) AS [BIRTH_DATE]
			,B.GENDER
			,A.DEP_DATE
			,A.NEW_DATE
			,DATEDIFF(DAY, A.NEW_DATE , A.DEP_DATE) AS 선행예약시점
		FROM RES_MASTER_damo A
		INNER JOIN RES_CUSTOMER_damo B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE
		INNER JOIN CUS_CUSTOMER_DAMO C ON B.CUS_NO = C.CUS_NO
		INNER JOIN PKG_DETAIL F ON A.PRO_CODE = F.PRO_CODE
		INNER JOIN PRO_TRANS_SEAT G ON F.SEAT_CODE =G.SEAT_CODE
		WHERE A.RES_STATE <=7  AND B.RES_STATE =0
		AND A.DEP_DATE >= '2015-01-01' AND A.DEP_DATE < '2016-01-01'
		AND A.PRO_TYPE = 1
		AND B.SALE_PRICE > 0
		
		AND G.DEP_ARR_AIRPORT_CODE IN ('HOE','LPQ','LXG','NEU','ODY','PKZ','THK','VNA','VNG','VTE','XAY','XKH','ZBY','ZVK')
) A
WHERE A.BIRTH_DATE IS NOT NULL
ORDER BY MONTH(A.DEP_DATE)