USE Diablo

SELECT KEYWORD, COUNT(*) AS ÃÑ°¹¼ö
FROM VGLOG..KEYWORD_LOG
WHERE(KEYWORD LIKE '%¶ó¿À½º%'
OR KEYWORD LIKE '%¹æºñ¿¨%'
OR KEYWORD LIKE '%ºí·ç¶ó±º%'
OR KEYWORD LIKE '%ºñ¿£Æ¼¿£%'
OR KEYWORD LIKE '%·ç¾ÓÇÁ¶ó¹æ%'
OR KEYWORD LIKE '%Äç½ÃÆøÆ÷%'
OR KEYWORD LIKE '%¿Ó½Ã»çÄÏ%'
OR KEYWORD LIKE '%Å¿·ç¾Ó%'
OR KEYWORD LIKE '%¶ó¿À%'
OR KEYWORD LIKE '%½ö°­%'
OR KEYWORD LIKE '%ºñ¿£Æ¼¾È%')
AND NEW_DATE >= '2016-01-01'
AND NEW_DATE < '2017-01-01'
GROUP BY KEYWORD
ORDER BY COUNT(*) DESC
