

DECLARE @START_DATE DATETIME, @END_DATE DATETIME
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 

SELECT @START_DATE = '2017-01-01', @END_DATE = '2018-01-01';

WITH LIST AS 
( 
SELECT dbo.BD_CUS_GET_AGE(B.BIRTH_DATE,A.DEP_DATE, 1 ) [AGE], isnull(B.GENDER,c.gender) as [gender], d.SIGN_CODE
	FROM RES_MASTER_DAMO A
	INNER JOIN RES_CUSTOMER_DAMO B ON A.RES_CODE = B.RES_CODE
	INNER JOIN CUS_CUSTOMER_damo C ON B.CUS_NO = C.CUS_NO
	INNER JOIN PKG_MASTER D ON A.MASTER_CODE = D.MASTER_CODE
	INNER JOIN PKG_DETAIL E  -- 출발자 
		ON A.PRO_CODE = E.PRO_CODE
	INNER JOIN PRO_TRANS_SEAT F  --좌석정보 
		ON E.SEAT_CODE = F.SEAT_CODE
	-- 부가 정보는 LEFT JOIN 사용 
	LEFT JOIN PUB_AIRPORT G  -- 공항정보 
		ON F.DEP_ARR_AIRPORT_CODE = G.AIRPORT_CODE  
	LEFT JOIN PUB_CITY H  -- 도시정보
		ON G.CITY_CODE = H.CITY_CODE 
	LEFT JOIN PUB_NATION I  -- 국가정보
		ON H.NATION_CODE = I.NATION_CODE 
	WHERE A.DEP_DATE >= @START_DATE AND A.DEP_DATE < @END_DATE AND A.RES_STATE < 7 AND B.RES_STATE = 0 AND SIGN_CODE = 'A'
	AND H.NATION_CODE = 'KH'
	)


	SELECT A.GENDER AS [성별], a.AGE as [연령대], B.KOR_NAME as [여행지역], COUNT(*) AS [인원수] 
	FROM LIST A
	LEFT JOIN PUB_REGION B ON A.SIGN_CODE =B.SIGN
	GROUP BY a.gender, a.age, B.KOR_NAME
	ORDER BY a.gender, a.age, B.KOR_NAME asc